version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: shoedidas_header
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql

  web:
    build: .
    environment:
      DB_USER_DEVELOPMENT: root
      DB_PASS_DEVELOPMENT: example
      DB_NAME_DEVELOPMENT: shoedidas_header
      DB_HOSTNAME: db
      PORT: 3000
      CDN_ROOT: https://s3-us-west-1.amazonaws.com/shoedidas-static
    ports:
      - "3000:3000"
    depends_on:
      - db