version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: shoedidas_header
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db