module.exports = ["NHL",
"MLS",
"College",
"Club",
"AFC Ajax",
"Anaheim Ducks",
"Argentina National Team",
"Arizona Coyotes",
"Arizona State University",
"Atlanta United",
"Belgium National Team",
"Benefica",
"Boston Bruins",
"Brazil National Team",
"Buffalo Sabres",
"Calgary Flames",
"Carolina Hurricanes",
"Chicago Blackhawks",
"Chicago Fire",
"Colombia National Team",
"Colorado Avalanche",
"Colorado Rapids",
"Columbus Blue Jackets",
"Columbus Crew",
"CSKA Moscow",
"D.C. United",
"Dallas Stars",
"Detroit Red Wings",
"East Carolina Pirates",
"Edmonton Oilers",
"FC Basel",
"FC Bayern Munich",
"FC Dallas",
"Flamengo",
"Florida Panthers",
"Georgia Tech",
"Germany National Team",
"Hamburger SV",
"Holy Cross Crusaders",
"Houston Dynamo",
"Houston Rockets",
"Indiana Hoosiers",
"Japan National Team",
"Juventus",
"Kansas Jayhawks",
"Leicester City FC",
"Los Angeles Football Club",
"Los Angeles Galaxy",
"Los Angeles Kings",
"Louisville Cardinals",
"Manchester United FC",
"Mexico National Team",
"Miami ",
"Miami Hurricanes",
"Minnesota United",
"Minnesota Wild",
"Mississippi",
"Mississippi State Bulldogs",
"Montreal Canadiens",
"Montreal Impact",
"Nashville Predators",
"National Hockey Team",
"NC State Wolfpack",
"Nebraska Cornhuskers",
"New England Revolution",
"New Jersey Devils",
"New York City FC",
"New York Islanders",
"New York Rangers",
"New York Red Bulls",
"Olympique Lyonnais",
"Orlando City SC",
"Ottawa Senators",
"Philadelphia Flyers",
"Philadelphia Union",
"Pittsburgh Penguins",
"Portland Timbers",
"Real Madrid",
"Real Salt Lake",
"Russia National Team",
"Rutgers Scarlet Knights",
"San Jose Earthquakes",
"San Jose Sharks",
"Seattle Sounders",
"Spain National Team",
"Sporting Kansas City",
"St Louis Blues",
"Sweden National Team",
"Tampa Bay Lightning",
"Texas A&M Aggies",
"Toronto FC",
"Toronto Maple Leafs",
"US National Team",
"Valencia CF",
"Vancouver Canucks",
"Vancouver Whitecaps",
"Vegas Golden Knights",
"Washington Capitals",
"Washington Huskies",
"Winnipeg Jets",
"Wisconsin Badgers"]